apiVersion: v1
data:
  ENVIRONMENT: cloud
  LOG_LEVEL: INFO
  MONGODB_HOST: mongodb-service
  REDIS_HOST: redis-service
kind: ConfigMap
metadata:
  name: soc-config
  namespace: soc-correlation-engine
