apiVersion: v1
data:
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXk=
  JWT_SECRET: c3VwZXJfc2VjcmV0X2tleQ==
  MONGODB_PASSWORD: YWRtaW4=
  REDIS_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: soc-secrets
  namespace: soc-correlation-engine
type: Opaque
